### ISSUE TITLE
IPNS resolution?

### ISSUE THREAD

**Issue by NoahZinsmeister** [wealdtech/coredns-ens#3]
Does the roadmap for this project include supporting resolution of IPNS pointers via ENS? Specifically, not just traditional IPNS pointers but also DNSLink-style ones.

The usecase here would be if a user adds a `_dnslink` `TXT` record to their domain, enabling `ipns/<domain>.<tld>` resolution, then they should be able to add this pointer as a field to their `<name>.ens` name, and `*.eth.link` should be able to perform the recursive lookup.

**Comment by mcdee** [comment]
This should operate correctly with the current implementation, for example:

```
$ ethereal ens contenthash get --domain=wealdtech.eth
/ipns/www.wealdtech.eth
```

And `http://wealdtech.eth.link` should resolve as expected.

**Comment by NoahZinsmeister** [comment]
Hm, what if you wanted to resolve to /ipns/<domain>.com, for example? My impression is that uploading records of this variety to the `contenthash` field of an ENS domain isn't possible, but I would love to be wrong!

**Comment by mcdee** [comment]
I can't think of a reason why it shouldn't work, do you have a `.com` domain with DNS link information I could test it on?

**Comment by NoahZinsmeister** [comment]
Yes, https://noahzinsmeister.com

**Comment by mcdee** [comment]
```
$ ethereal ens contenthash set --domain=mcdee.eth --content=/ipns/noahzinsmeister.com
0x5239ce0b2ac9edf583ebfe65843bf66dc6bd2d383d5fcaf52f4ef4d20300a2f3
$ ethereal ens contenthash get --domain=mcdee.eth
/ipns/noahzinsmeister.com
```

https://mcdee.eth.link/  appears to resolve as expected.

**Comment by NoahZinsmeister** [comment]
😍 cool! Will try this out shortly, thank you for the prompt replies.

**Comment by NoahZinsmeister** [comment]
Works like a charm, thanks! I'm not 100% clear on how ethereal is doing the encoding of `/ipns/noahzinsmeister.com`, but that's out of scope and something I can look into separately. For now, I just copied your tx data to get it to work 😛.

**Comment by parkan** [comment]
@NoahZinsmeister it's a multicodec IPNS path:

`0xe5` is IPNS (as per https://github.com/multiformats/multicodec/blob/master/table.csv#L70), see https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1577.md and https://github.com/multiformats/multicodec/ for more info

you can use a multicodec lib like https://multiformats.github.io/js-multicodec/ to see for yourself
