### ISSUE TITLE
*.eth.link resolution errors

### ISSUE THREAD

**Issue by NoahZinsmeister** [wealdtech/coredns-ens#5]
Hi! Apologies if this isn't the right place for this question, but I recently noticed what may be a bug in `*.eth.link` domains.

Visiting e.g.`tokens.uniswap.eth.link` gives a Cloudflare `Error 1001` page, whereas running `ethereal ens contenthash get --domain=tokens.uniswap.eth` correctly returns `/ipns/tokens.uniswap.org`.

I believe this issue may manifest only for nested ENS names?

**Comment by mcdee** [comment]
I believe this was a transition issue due to the `eth.link` servers changing administrator, and should be fixed.

Issues about the operation of the `eth.link` domains can be raised at the ENS Discord, at https://discord.gg/TNDVT2X
