### ISSUE TITLE
Return DNS TXT with DNSLink on _dnslink.

### ISSUE THREAD

**Issue by lidel** [wealdtech/coredns-ens#6]
The best practice is to expose it on `_dnslink.example.eth` but this project exposes them only on `example.eth`
Ref. https://docs.ipfs.io/concepts/dnslink/

It is ok to expose it on both, but this project should add support for TXT records on  `_dnslink.example.eth` because user agents like Brave will do single lookup only for that name.

**Comment by lidel** [comment]
@mcdee was this fixed in f86ef11?

**Comment by mcdee** [comment]
Yeah.  Looks like a typo in the commit comment stopped it from auto-closing this issue.
